apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: go
spec:
  selector:
    matchLabels:
      app: go
      tier: interface
  replicas: 1
  template:
    metadata:
      labels:
        app: go
        tier: interface
    spec:
      containers:
      - name: nginx
        image: "erik/go-web-app"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080

