apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: go
    tier: interface
  ports:
  - name: webserver
    port: 8080
    targetPort: 8080
  selector:
    app: go
    tier: interface