apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: go
    tier: interface
  ports:
  - name: go
    port: 8080
    targetPort: 8080
  selector:
    matchLabels:
      app: go
      tier: interface